### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by vals** [asncd/MIMOSCA#1]
Hey, great work. The linear model seems like a great idea. In particular the single EM step!

I can't seem to find the actual code here though? Just READMEs?

Am I missing something?

**Comment by asncd** [comment]
Hi Val,

There's code in the subfolders, this is an example comparing to population RNA-seq knockout data: 
https://github.com/asncd/MIMOSCA/blob/master/Power_Analysis_DOE/ost_ko_comparison.ipynb

The EM code isn't included only because I was hoping to update it slightly before releasing

If there is anything else specific you'd like, let me know and I'll upload it.

**Comment by vals** [comment]
Hi Atray,

Things I would be interested to see would be

 - How the cell state definition is run, with all the many steps.
 - How the covariate matrix is created
 - How you perform the variance decomposition of technical factors
 - How you infer perturbation probability
 - How the significance of linear coefficients is calculated
 - How you find the model R2
 - How you associate PCA loadings with biological terms
 - How you run the jackstraw analysis

**Comment by asncd** [comment]
Cool, I'll have those up in the next few days.

**Comment by asncd** [comment]
Hi Val,

I uploaded a library of code  mimosca.py that contains most of the function calls that may be of interest (highlighted below). Note that the goatools packages will likely need to be installed to run the go portion of the code...but can be commented out if you don't need to run that portion.

-Cell state definition: see new ipython notebook in the Cell_State folder (also has an example of the PCA loadings -> GO terms and jackstraw usage)

-Variance decomposition is based on Model R^2 is calculated by training on some of the data and evaluating on the holdout (see the marginal_covariates function)...decomposition into the technical factors is evaluated by only using those factors as covariates and evaluating R^2. 

-Perturbation probability (run_model_bycol and bayes_cov_col are the relevant functions), I'll create a worked example of this in the near future

-Significance of linear coefficients (make_shufs and fdr_colwise_coefs) see the example here (https://github.com/asncd/MIMOSCA/blob/master/Power_Analysis_DOE/ost_ko_comparison.ipynb)

Let me know if you come across any bugs, issues, or would like better documentation. 

Best,
Atray
