### ISSUE TITLE
GBC/CBC dictionary creation

### ISSUE THREAD

**Issue by jan-glx** [asncd/MIMOSCA#2]
In the readme in the https://github.com/asncd/MIMOSCA/tree/master/GBC_CBC_pairing folder, it says there would be a 

> - iPython notebook containing example of processing counts table into GBC/CBC dictionary

but I can not find it anywhere. Would you mind to point me to it/upload it?

**Comment by asncd** [comment]
oops, sorry I'll upload it later today

**Comment by asncd** [comment]
Hi Jan,

I uploaded an iPython notebook called guide_cbc_dictmaker with the relevant data files in a subfolder called small data. 

notes:
-for alignment: you could alternatively build a bowtie index for the cell barcodes and the guide barcodes and align them externally...which might be helpful for larger numbers of cells/guide barcodes
-For such applications, I have a hashed edit distance calculator, that's quite a bit faster, if you are interested...

Let me know if you have questions.

Best,
Atray

**Comment by jan-glx** [comment]
Thanks! Code is often so much clearer than text :)
