### ISSUE TITLE
Hard to use

### ISSUE THREAD

**Issue by BinDuan** [asncd/MIMOSCA#4]
There is no an example showing us how to use it. I mean, how to deal with the inputs and finally get the results. I don't know how should I use MIMOSCA to get the final results.

**Comment by asncd** [comment]
my apologies for the lack of clarity. Is there a specific section of the [computational workflow](https://github.com/asncd/MIMOSCA#computational-workflow) that you would like more information regarding? 

[This](https://github.com/asncd/MIMOSCA/blob/master/Power_Analysis_DOE/ost_ko_comparison.ipynb) might be a good starting point as far as scripts go if you already have your input data formatted.

Best,
Atray

**Comment by BinDuan** [comment]
Thank you for your reply.

 I'm sorry I didn't make my question understood. I want to use MIMOSCA to run all the pipeline with the standard inputs you provided, but it seems that there is no a detail example to tell me how should I get the final results such as the effect of cell states to a perturbation. What you provided were some components in your pipeline. Therefore, I wonder how to use it. Can you provided a whold example from the standard inputs to the final results with MIMOSCA?

**Comment by asncd** [comment]
I'll provide a more annotated example for you in a couple weeks!

**Comment by kaanokay** [comment]
Dear @asncd,

First of all, I'd like thank you for developing such nice pipeline. I have the same issue that @BinDuan encountered. I want to obtain cell-by-perturbation UMI matrix by using your pipeline, but it is very complex for me. I'm planning to use 10x Genomics 3' v3 kit to create scRNA libraries. How can I obtain cell-by-perturbation matrix from fastq files of each sample? After obtaining this matrix, I will pair cell and perturbation barcodes. Could you provide a pipeline for me? It's really complex to understand and get final outputs. Thank your for your interest.

Best.

**Comment by Amybio** [comment]
Dear @asncd ,
The MIMOSCA pipeline seems a bit complex for me. Could you please provide a complete example code for this pipeline to me? 
Best
